kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: vgw
  labels:
    service: vgw
spec:
  replicas: 1
  selector:
    matchLabels:
      service: vgw
  template:
    metadata:
      labels:
        service: vgw
    spec:
      volumes:
#      - persistentVolumeClaim:
#          claimName: recordings
#        name: recordings
#
#      - name: unimrcpconfig
#        secret:
#          secretName: unimrcp-config-secret
#          items:
#          - key: unimrcpConfig
#            path: unimrcpclient.xml
#
# Volumes for SSL configuration
# Sip Orchestrator
#      - name: ssl-so
#        secret:
#          secretName: trust-store-file-secret
#          items:
#          - key: "trustStoreFile"
#            path: "trustStoreFile"
# Media Relay
#      - name: ssl-mr-mutualauth
#        secret:
#          secretName: ssl-client-pkcs12-file-secret
#          items:
#          - key: "clientPkcs12File"
#            path: "clientPkcs12File"
#      - name: ssl-mr
#        secret:
#          secretName: client-ca-cert-secret
#          items:
#          - key: "clientCaCertFile"
#            path: "clientCaCertFile"
      - name: tenantconfig
        secret:
          secretName: tenantconfig
          items:
          - key: tenantConfig
            path: tenantConfig.json
      hostNetwork: true
      containers:
      - name: vgw-media-relay
        image: ibmcom/voice-gateway-mr:latest
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/quiesce.sh"
        env:
        - name: SDP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ENABLE_RECORDING
          value: 'false'
        - name: RTP_UDP_PORT_RANGE
          value: 16384-16584
        - name: CLUSTER_WORKERS
          value: '0'
        - name: MEDIA_RELAY_LOG_LEVEL
          value: DEBUG
        - name: MEDIA_RELAY_WS_PORT
          value: '8080'

#        - name: SSL_CLIENT_CA_CERTIFICATE_FILE
#          value: "/sslConf/clientCaCertFile"
        
#        - name: SSL_CLIENT_PKCS12_FILE
#          value: "/sslConf/clientPkcs12File"
#        - name: SSL_CLIENT_PASSPHRASE
#          valueFrom:
#            secretKeyRef:
#              name: ssl-client-passphrase-secret
#              key: sslClientPassphrase



        volumeMounts:
#        - name: recordings
#          mountPath: "/vgw-media-relay/recordings"
#
#        - name: unimrcpconfig
#          mountPath: "/vgw-media-relay/config/unimrcpclient.xml"
#          subPath: "unimrcpclient.xml"
#

#        - name: ssl-mr
#          mountPath: "/sslConf/clientCaCertFile"
#          subPath: "clientCaCertFile"
#        - name: ssl-mr-mutualauth
#          mountPath: "/sslConf/clientPkcs12File"
#          subPath: "clientPkcs12File"

        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: Always
      - name: vgw-sip-orchestrator
        image: ibmcom/voice-gateway-so:latest
        ports:
        - containerPort: 5060
          hostPort: 5060
          protocol: TCP
        - containerPort: 5060
          hostPort: 5060
          protocol: UDP
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/quiesce.sh"
        env:
        - name: SIP_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MEDIA_RELAY_HOST
          value: localhost:8080
        - name: SIP_PORT
          value: '5060'
        - name: HTTPS_PORT
          value: '9443'
        - name: HTTP_HOST
          value: 127.0.0.1
        - name: ENABLE_AUDIT_MESSAGES
          value: 'true'
        - name: ENABLE_TRANSCRIPTION_AUDIT_MESSAGES
          value: 'true'
        - name: LOG_LEVEL
          value: all
        - name: MULTI_TENANT_CONFIG_FILE
          value: "/tenantconfig/tenantConfig.json"

#        - name: SSL_KEY_TRUST_STORE_FILE
#          value: "/sslConf/trustStoreFile"
#        - name: SSL_FILE_TYPE
#          value: "JKS"
#        - name: SSL_PASSPHRASE
#          valueFrom:
#            secretKeyRef:
#              name: ssl-passphrase-secret
#              key: sslPassphrase

        volumeMounts:
        - name: tenantconfig
          mountPath: "/tenantconfig/tenantConfig.json"
          subPath: tenantConfig.json
#        - name: ssl-so
#          mountPath: "/sslConf/trustStoreFile"
#          subPath: "trustStoreFile"

        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
      dnsPolicy: ClusterFirstWithHostNet